name: Sonar Code Review Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3  # Updated to v3
        with:
          fetch-depth: 0  # Ensure a full clone for better relevancy of analysis

      - uses: sonarsource/sonarqube-scan-action@v2  # Use stable version v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Optional: Fail job if Quality Gate fails
      # - uses: sonarsource/sonarqube-quality-gate-action@v2
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
