name: Build Workflow

on:
  workflow_run:
    workflows:
      - Sonar Code Review Workflow
    types:
      - completed

jobs:
  build-push-image:
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3 # Updated to v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      - name: Install kubectl
        run: gcloud components install kubectl --quiet

      - name: Check kubectl version
        run: kubectl version --client

      - name: Display gcloud CLI info
        run: gcloud info

      - name: Docker Authentication
        run: gcloud auth configure-docker europe-west9-c-docker.pkg.dev --quiet

      - name: Set version
        id: version
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          VERSION: ${{ env.VERSION }}
        run: |
          DOCKER_IMAGE="europe-west9-c-docker.pkg.dev/${GOOGLE_PROJECT}/frontend/react-gcp:${VERSION}"
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
